### ISSUE TITLE
Provide Sentinel Connector as an artifact or base Docker image

### ISSUE THREAD

**Issue by patheard** [cds-snc/aws-sentinel-connector-layer#7]
# Summary
For projects using this connector as part of a Lambda Docker image, it would be nice if there was a way to pull versions of the code either as an artifact or as part of a Docker image.

The behaviour we're currently seeing in one of our projects is that the previous layers are being deleted as new layers are published.  This results in failed builds as we're [hardcoding the layer we need to download](https://github.com/cds-snc/security-tools/blob/2526699859c47f33e2f60ac5542cefa30ce03370/.github/workflows/ci_build_containers.yml#L68), which is a requirement of specifying a layer ARN.

# Notes
If this became a public Docker image, we could take advantage of Renovate auto updates.

# Related
- cds-snc/security-tools#73

**Comment by patheard** [comment]
@ascheid take a look at options for how we could serve the layer code.  The two options I can think of are:

- Artifact that gets stored as part of this repo; or
- public docker image in our ECR that other projects can use as a base image.

**Comment by ascheid** [comment]
Image is being stored in our AWS ECR. It is already being used by security-tools.
